name: WarpUI-SPNVN
main: Github\WarpUI\Main
api:
 - 3.0.0
 - 3.2.0
version: 3.5
author: BlackPMFury
softDepends: [FormAPI]
descriptions: "What's new at Version 3.5? It's Class UI and Admin tools."
commands:
 warpui:
  description: "WarpUI SPNVN"
  usage: /warpui
  default: true
 WarpUI:
  description: "WarpUI SPNVN"
  usage: /WarpUI
  default: true
 Warpui:
  description: "WarpUI SPNVN"
  usage: /Warpui
  default: true